version: '3'

services:
  logger:
    container_name: lab42_logger_php
    build: .
    user: www-data
    volumes:
      - .:/opt/app
    depends_on:
      - clickhouse

  clickhouse:
    container_name: lab42_logger_clickhouse
    image: yandex/clickhouse-server:21.3.20.1-alpine
    ports:
      - "8123:8123"
    volumes:
      - /var/data/lab42_logger/clickhouse:/var/lib/clickhouse
